name:                GitClone
version:             0.1.0.0
github:              "srodman7689/GitClone"
license:             BSD3
author:              "Sean Rodman"
maintainer:          "srodman7689@gmail.com"
copyright:           "2018 Sean Rodman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/srodman7689/GitClone#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- network

library:
  source-dirs: src

executables:
  GitClone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GitClone

tests:
  GitClone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GitClone
